services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    tty: true

  web:
    build:
      context: ./ihm
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - rabbitmq